# Generated by Django 4.2.3 on 2023-07-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_parent', models.CharField(max_length=20)),
                ('email_parent', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.CharField(choices=[('Petite Section', 'Petite Section'), ('Moyenne Section', 'Moyenne Section'), ('Grande Section', 'Grande Section')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[('Petite Section', 'Petite Section'), ('Moyenne Section', 'Moyenne Section'), ('Grande Section', 'Grande Section')], editable=False, max_length=15)),
                ('Dessin', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Ecriture', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Chant', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Cumule', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joupilou_members.children')),
            ],
        ),
    ]
