# Generated by Django 4.2.3 on 2023-07-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joupilou_members', '0002_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
    ]
