# Generated by Django 4.2.3 on 2023-07-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joupilou_members', '0003_remove_contactmessage_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
