# Generated by Django 4.2.3 on 2023-07-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joupilou_members', '0004_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('objet', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
